### ISSUE TITLE
Compatibility with Watch mode

### ISSUE THREAD

**Issue by joelzimmer** [palmerj3/jest-unique-reporter#4]
Running this with `--watchAll` seems to not clear the list of duplicate test names, so subsequent runs of the test suite will cause *all* tests to be flagged as duplicate names

**Comment by palmerj3** [comment]
@joelzimmer thank you for submitting an issue!

I would actually highly recommend using eslint-plugin-jest since it has a duplicate test name check. I intend on deprecating this repo and suggesting that.

https://github.com/jest-community/eslint-plugin-jest

**Comment by joelzimmer** [comment]
Thanks! maybe add a note to the readme with that if you can

**Comment by palmerj3** [comment]
Absolutely
